Repository treslebr/laravel-api, pull requests merged in 2019-08, with the labels that each got.

#13 Realizar validações das requisições 404 e produtos adicionais
  tresle/Product/Http/Controllers/Additional/AdditionalController.php
  tresle/Product/Http/Requests/Additional/AdditionalRequest.php
  tresle/Product/Routes/api.php
Labels: bug

#20 CRUD Endereços do cliente
  app/Http/Kernel.php
  tresle/Customer/Http/Controllers/CustomerAddressController.php
  tresle/Customer/Http/Controllers/CustomerController.php
  tresle/Customer/Http/Requests/CustomerAddressRequest.php
  tresle/Customer/Migrations/2019_08_13_013943_create_customer_address.php
  tresle/Customer/Model/Address/Address.php
  tresle/Customer/Model/Customer/Customer.php
  tresle/Customer/Routes/api.php
  tresle/User/Http/Auth/AuthController.php
  tresle/User/Http/Middleware/AuthCustomer.php
  tresle/User/Model/User.php
Labels: Feature

#22 PATCH no módulo de Produto
  tresle/Product/Http/Requests/Additional/AdditionalCategoryRequest.php
  tresle/Product/Http/Requests/Additional/AdditionalRequest.php
  tresle/Product/Http/Requests/Product/ProductCategoriesRequest.php
  tresle/Product/Http/Requests/Product/ProductRequest.php
Labels: enhancement

#24 Frete
  config/app.php
  database/seeds/UserTableSeeder.php
  tresle/Customer/Http/Controllers/CustomerAddressController.php
  tresle/Customer/Http/Requests/CustomerAddressRequest.php
  tresle/Customer/Migrations/2019_08_13_013943_create_customer_address.php
  tresle/Customer/Model/Address/Address.php
  tresle/Shipping/Http/Controllers/ShippingController.php
  tresle/Shipping/Http/Requests/Shipping.php
  tresle/Shipping/Migrations/2019_05_14_003634_create_shipping.php
  tresle/Shipping/Model/Shipping.php
  tresle/Shipping/Providers/ShipppingServiceProvider.php
  tresle/Shipping/Routes/api.php
  tresle/User/Http/Auth/AuthController.php
Labels: Feature

#26 Carrinho de compras
  config/app.php
  database/seeds/AdditionalCategoryTableSeeder.php
  database/seeds/AdditionalTableSeeder.php
  database/seeds/ProductCategoryTableSeeder.php
  database/seeds/ProductTableSeeder.php
  tresle/Cart/Http/Controllers/CartController.php
  tresle/Cart/Http/Requests/CartRequest.php
  tresle/Cart/Migrations/2019_08_17_130237_create_cart.php
  tresle/Cart/Model/Cart.php
  tresle/Cart/Model/CartQuery.php
  tresle/Cart/Providers/CartServiceProvider.php
  tresle/Cart/Routes/api.php
  tresle/Product/Http/Requests/Product/ProductRequest.php
Labels: Feature

#28 Pedidos
  config/app.php
  database/seeds/DatabaseSeeder.php
  database/seeds/UserTableSeeder.php
  tresle/Cart/Http/Controllers/CartController.php
  tresle/Cart/Http/Requests/CartRequest.php
  tresle/Customer/Http/Controllers/CustomerAddressController.php
  tresle/Customer/Http/Controllers/CustomerController.php
  tresle/Customer/Routes/api.php
  tresle/Order/Http/Controllers/OrderController.php
  tresle/Order/Http/Requests/OrderRequest.php
  tresle/Order/Migrations/2019_08_18_234226_create_order.php
  tresle/Order/Migrations/2019_08_19_004141_create_order_item.php
  tresle/Order/Migrations/2019_08_19_004730_create_order_item_additional.php
  tresle/Order/Model/Order.php
  tresle/Order/Model/OrderItem.php
  tresle/Order/Model/OrderItemAdditional.php
  tresle/Order/Model/OrderQuery.php
  tresle/Order/Providers/OrderServiceProvider.php
  tresle/Order/Routes/api.php
Labels: Feature

#30 Melhorando código de status das requisições da API
  tresle/Cart/Http/Controllers/CartController.php
  tresle/Customer/Http/Controllers/CustomerAddressController.php
  tresle/Customer/Http/Controllers/CustomerController.php
  tresle/Customer/Model/Address/AddressQuery.php
  tresle/Order/Http/Controllers/OrderController.php
  tresle/Product/Http/Controllers/Additional/AdditionalController.php
  tresle/Product/Http/Controllers/Additional/CategoryController.php
  tresle/Product/Http/Controllers/Product/CategoryController.php
  tresle/Product/Http/Controllers/Product/ImageController.php
  tresle/Product/Http/Controllers/Product/ProductController.php
  tresle/Shipping/Http/Controllers/ShippingController.php
  tresle/User/Http/Auth/AuthController.php
Labels: enhancement

#32 Adicionar autenticação nas rotas.
  tresle/Cart/Model/Cart.php
  tresle/Cart/Model/CartQuery.php
  tresle/Order/Model/Order.php
  tresle/Product/Http/Controllers/Product/ProductController.php
  tresle/Product/Routes/api.php
  tresle/User/Model/User.php
Labels: Feature
